apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    generation: 5
    name: aims-db
    namespace:  {{ .Values.namespace }}
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: aims-db
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: aims-db
      spec:
        containers:
        - env:
          - name: POSTGRESQL_DATABASE
            value: aims
          - name: POSTGRESQL_PASSWORD
            value: microsafe.2022
          - name: POSTGRESQL_EXTRA_FLAGS
            value: --max_connections=600 --shared_buffers=80MB
          image: devmicrosafe/aims-db@sha256:885f2a0fc5579c2f8c644f1c0b9be9495fc98b65c2965267863cbd58f6c8bb63
          imagePullPolicy: IfNotPresent
          name: aims-db
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            seccompProfile:
              type: RuntimeDefault
          ports:
          - containerPort: 5432
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /docker-entrypoint-preinitdb.d
            name: aims-db-3
          - mountPath: /docker-entrypoint-initdb.d
            name: aims-db-2
          - mountPath: /bitnami/postgresql
            name: aims-db-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        securityContext: {}
        volumes:
        - emptyDir: {}
          name: aims-db-3
        - name: aims-db-2
          persistentVolumeClaim:
            claimName: aims-init-storage
        - name: aims-db-1
          persistentVolumeClaim:
            claimName: aims-db-storage
        - emptyDir: {}
          name: default-token-l4tgm
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "4"
    generation: 4
    name: aims-gql
    namespace:  {{ .Values.namespace }}
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: aims-gql
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: aims-gql
      spec:
        containers:
        - env:
          - name: POSTGRESQL_URL
            value: postgres://postgres:microsafe.2022@aims-db/aims
          image: devmicrosafe/aims-gql@sha256:0be844db21f2d665ec51c6bbd7bffd09f1155b59f2dc42a03ab29dd6f2f21a3f
          imagePullPolicy: IfNotPresent
          name: aims-gql
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            seccompProfile:
              type: RuntimeDefault
          ports:
          - containerPort: 5430
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        securityContext: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "9"
    generation: 11
    name: aims-http
    namespace:  {{ .Values.namespace }}
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: aims-http
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: aims-http
      spec:
        containers:
        - env:
          - name: GRAPHQL_URL
            value: http://aims-gql.microsafe.com.mx
          - name: AIMSWS_URL
            value: http://aims-ws.microsafe.com.mx
          image: devmicrosafe/aims-http@sha256:1312e51a204d5b96eec0e8863e0f513b7dc572dfd632146ff0b1a5e100a2afe2
          imagePullPolicy: IfNotPresent
          name: aims-http
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            seccompProfile:
              type: RuntimeDefault
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        securityContext: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "4"
    generation: 4
    name: aims-ws
    namespace:  {{ .Values.namespace }}
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: aims-ws
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: aims-ws
      spec:
        containers:
        - env:
          - name: AIMSWS_PORT
            value: "8081"
          - name: POSTGRESQL_URL
            value: postgres://postgres:microsafe.2022@aims-db/aims
          - name: EMAIL_SERV_URL
            value: email://user:pass@host:port/sender_account@server.com
          - name: AIMSAPP_URL
            value: http://aims-http.microsafe.com.mx
          - name: GRAPHQL_URL
            value: http://aims-gql.microsafe.com.mx
          image: devmicrosafe/aims-ws@sha256:5b568bb96ee5d6ffce20356812d4a80adbfe9ebefa250b9a80e9faee3556a21f
          imagePullPolicy: IfNotPresent
          name: aims-ws
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            seccompProfile:
              type: RuntimeDefault
          ports:
          - containerPort: 8081
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        securityContext: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    generation: 1
    name: comm-db
    namespace:  {{ .Values.namespace }}
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: comm-db
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: comm-db
      spec:
        containers:
        - env:
          - name: POSTGRESQL_DATABASE
            value: aimsdata
          - name: POSTGRESQL_PASSWORD
            value: microsafe.2022
          - name: POSTGRESQL_EXTRA_FLAGS
            value: --max_connections=600 --shared_buffers=80MB
          image: devmicrosafe/comm-db@sha256:6707eab1c8a32de31a4ea133cbcdd1657ae11be8b5221d57af3f4d480f341ffb
          imagePullPolicy: IfNotPresent
          name: comm-db
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            seccompProfile:
              type: RuntimeDefault
          ports:
          - containerPort: 5432
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /docker-entrypoint-preinitdb.d
            name: comm-db-3
          - mountPath: /docker-entrypoint-initdb.d
            name: comm-db-2
          - mountPath: /bitnami/postgresql
            name: comm-db-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        securityContext: {}
        volumes:
        - emptyDir: {}
          name: comm-db-3
        - name: comm-db-2
          persistentVolumeClaim:
            claimName: comm-init-storage
        - name: comm-db-1
          persistentVolumeClaim:
            claimName: comm-db-storage
        - emptyDir: {}
          name: default-token-l4tgm
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "3"
    generation: 3
    name: comm-ws
    namespace:  {{ .Values.namespace }}
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: comm-ws
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: comm-ws
      spec:
        containers:
        - env:
          - name: COMMWS_PORT
            value: "9000"
          - name: POSTGRESQL_APP_URL
            value: postgres://postgres:microsafe.2022@aims-db/aims
          - name: POSTGRESQL_TRN_URL
            value: postgres://postgres:microsafe.2022@comm-db/aimsdata
          image: devmicrosafe/comm-ws@sha256:d504bbb771285c2ef4c2b571c488fde8b3047c2aec03a54d4f0c92a809b7f852
          imagePullPolicy: IfNotPresent
          name: comm-ws
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            seccompProfile:
              type: RuntimeDefault
          ports:
          - containerPort: 9000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        securityContext: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "3"
    generation: 3
    name: data-svc
    namespace:  {{ .Values.namespace }}
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: data-svc
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: data-svc
      spec:
        containers:
        - env:
          - name: POSTGRESQL_APP_URL
            value: postgres://postgres:microsafe.2022@aims-db/aims
          - name: POSTGRESQL_TRN_URL
            value: postgres://postgres:microsafe.2022@comm-db/aimsdata
          image: devmicrosafe/data-svc@sha256:45cb74e3085f629028e2bf1718363611e6e2ebea0b39b071a1c3a7d9c2c696af
          imagePullPolicy: IfNotPresent
          name: data-svc
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            seccompProfile:
              type: RuntimeDefault
          ports:
          - containerPort: 9001
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        securityContext: {}
kind: List
metadata:
  resourceVersion: ""
