apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: aims-db
    namespace: {{ .Values.namespace }}
  spec:
    clusterIP:
    clusterIPs:
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: aims-db
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: aims-gql
    namespace: {{ .Values.namespace }}
  spec:
    clusterIP:
    clusterIPs:
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 5430
      protocol: TCP
      targetPort: 5430
    selector:
      app: aims-gql
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: aims-http
    namespace: {{ .Values.namespace }}
  spec:
    clusterIP:
    clusterIPs:
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: aims-http
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: aims-ws
    namespace: {{ .Values.namespace }}
  spec:
    clusterIP:
    clusterIPs:
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      app: aims-ws
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: comm-db
    namespace: {{ .Values.namespace }}
  spec:
    clusterIP:
    clusterIPs:
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: comm-db
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: comm-ws
    namespace: {{ .Values.namespace }}
  spec:
    clusterIP: 
    clusterIPs:
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      app: comm-ws
    sessionAffinity: None
    type: ClusterIP
kind: List
metadata:
  resourceVersion: ""
